### ISSUE TITLE
Multiple build on same target mess up output folding 

### ISSUE THREAD

**Issue by kevinresol** [back2dos/travix#13]

**Comment by back2dos** [comment]
My guess is that folding tags need to be unique?

**Comment by kevinresol** [comment]
Yes, i think so. Maybe we can make use of environment variables to store some counters across runs.

**Comment by kevinresol** [comment]
Hmm.. seems that each travix process is spawned as a child of the haxelib process so that any environment variable set does not persist across travix processes. I ended up using a file to store that.

**Off-topic:**
Anyway, I just noticed that travix's own test merely `haxelib dev .` to link up the travix lib. But there is no `run.n` in the repo. So does that mean we don't need to actually [build the run.n before submitting](https://github.com/back2dos/travix/blob/a5809e3333878d0af842e395478375607e30e053/submit.sh#L3)? I am really confused with this, I thought I need to submit run.n in the zip to lib.haxe.org....

Can anyone explain it a bit?

**Comment by back2dos** [comment]
Uhm, yeah, there is a practically undocumented feature in haxelib, that allows to specify a main class in the `haxelib.json` which, when defined (as [in travix' case](https://github.com/back2dos/travix/blob/master/haxelib.json#L2)) takes [precedence over the `run.n`](https://github.com/HaxeFoundation/haxelib/blob/development/src/haxelib/client/Main.hx#L1383). In that case the relatively recent (compared to haxelib itself) `haxe --run` is used for running the library.

I chose this because:

1. on some obscure environments neko is not in fact installed
2. locally I don't need to ever rebuild travix

But at the bottom line I don't think it really matters ;)

**Comment by kevinresol** [comment]
Gosh.. that tricked me to add that build.hxml file lol. Anyway I have reverted that.
Should have added that here http://haxe.org/manual/haxelib-json.html...
