### ISSUE TITLE
Flash on travis

### ISSUE THREAD

**Issue by benmerckx** [back2dos/travix#21]
Since the new release, [testing tink_await](https://travis-ci.org/haxetink/tink_await/jobs/135797900) on flash fails with: 
```
Xlib:  extension "RANDR" missing on display ":99".
Vector smash protection is enabled.
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```
I'm unsure if this is a problem in travix, or buddy. Maybe async buddy tests don't exit right?
@ciscoheat

**Comment by back2dos** [comment]
You [need to add some more parameters](https://github.com/back2dos/travix#building-for-flash): `-D flash-exit -D reporter=buddy.reporting.TraceReporter`

@ciscoheat I do wonder whether this could not be simplified. Do you see an issue with making `-D flash-exit` the default in `haxelib run travix flash`?

**Comment by ciscoheat** [comment]
Good idea, that'll simplify things. Same with a default value for reporter?

Den tis 7 jun 2016 10:26Juraj Kirchheim <notifications@github.com> skrev:

**Comment by back2dos** [comment]
I'm not really sure about that. Wanting your flash tests to exit on travis is probably a nobrainer. But if you has a fancy reporter yourself, then you might want to have a way to set that. I'm not sure how the compiler deals with redefinition of flags, but if there's a simple way to make this an overrideable default also, then I'm all for it.

**Comment by ciscoheat** [comment]
I was thinking since we have the args in `this.args`, we can just parse them for `-D [regexp]` and set a default if it doesn't exist, for any target we'd like?

**Comment by back2dos** [comment]
That is possible, yes, but additional args may come from the `tests.hxml` (or the hxmls it references) and also from other libraries (e.g. some library wrapped around buddy, that brings it's own uber-reporter and other convenience features). It's not very likely, but I wouldn't want to kill the opportunity before it was explored. Particularly since this is the kind of thing we probably won't get to change without breaking other people's setup.

But my naive hope is that you just have to make sure that the `-D reporter` comes first or last and it'll be fine.

Another option would be to have buddy pick the "right" reporter. The macro that determines it can check the environment for travis and then default to `TraceReporter` if nothing is set. That would also make using buddy without travix easier.

**Comment by ciscoheat** [comment]
Yes it's tricky considering all circumstances, yet this flash case is quite special. But a combination of automatically setting `-D flash-exit` in travix, and letting buddy determine default reporter should be fine. I'll take care of that.

**Comment by ciscoheat** [comment]
@back2dos should be working fine now, so you can release a new version!

**Comment by kevinresol** [comment]
In [this build](https://travis-ci.org/haxetink/tink_await/jobs/135906720), seems that the flash tests has run and passed. But it tried it run it again and somehow failed at the end...

**Comment by back2dos** [comment]
Uhm, the thing is that flash sometimes non-deterministically hangs (I think I had this two times out of maybe 10), in which case the testcase fails. Maybe we could tune the timeout. What do you think @ciscoheat ?

**Comment by ciscoheat** [comment]
Yes, there's a new non-deterministic case that I haven't seen before, it could be because travis now runs on Ubuntu 14 instead of 12. 

The mentioned build is a good example. It seems to go well, but then at https://travis-ci.org/haxetink/tink_await/jobs/135906720#L1137-L1141 it fails with `xvfb-run: error: Xvfb failed to start`, and when it starts doing that for some reason, it's doomed to fail no matter how many times it's restarted. So it's not even about the number of retries anymore.

A workaround could be to check `flashlog.txt` for `x specs, y failures, z pending` and determine the outcome from there. Which is a buddy-specific solution, of course. I'm tired of the trial-and-error testing, so I'd be happy to go for that.

**Comment by ciscoheat** [comment]
I would use both methods, so if the build fails, it checks flashlog.txt.

**Comment by back2dos** [comment]
I'm fine with anything that works, but I wonder if flash can even run without xvfb?

**Comment by ciscoheat** [comment]
It seem to always run at least one time before crashing, so I'm hoping for that much determinism at least. :)

**Comment by ciscoheat** [comment]
I haven't checked into that, but I'll go for the flashlog.txt solution for now.

**Comment by kevinresol** [comment]
Maybe @andyli can give us some hints about testing flash.

For Andy: TL;DR;
Flash with xvfb seem to hang / crash / won't start in some undeterministic way. What we do now is to [retry a few times](https://github.com/back2dos/travix/blob/3f4c423312297a128a272ff8f4801468588471ac/src/travix/Travix.hx#L540-L544) and hopefully it will work for at least once. I would like to know what approach you are using on Haxe's tests and see if we have a chance to not hack like that?

**Comment by andyli** [comment]
It is somehow related to `flash.system.System.exit()`. For the haxe repo, in which we do not use `flash.system.System.exit()`, it works without any problem on Linux.
It may be a good idea to give up `flash.system.System.exit()` and just look at the flashlog.txt to determine test result.

**Comment by ciscoheat** [comment]
We're doing both at the moment, but it's difficult to make a general solution for checking flashlog.txt, it's checking for buddy only right now. But I could add utest as well, and we should be covered for most cases. Good enough?
