### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by kevinresol** [back2dos/travix#25]
I started to feel that travix needs to be configurable. For example, on flash tests we might need some configuration to tell travix how to read the flashlog.txt file. Recently I am looking at js tests with phantomjs, for which travix also needs to know how to read the results from the web page.

I suggest having a `.travix` file at the root and for now it has a structure similar to this:
```haxe
{
  flash: {
    flashlogRegex: "^[0-9]+ specs, 0 failures, [0-9]+ pending$$"
  },
  js: {
    index: "./index.html",
    pollVariable: "utest_result"
  }
}
```
For the format, yaml is easier to write, but it requires a dependency. So we can use json, which should be good enough.

**Comment by back2dos** [comment]
Given how tricky all the integrating is becoming, I'm somewhat inclined to actually turn things around: define a very basic interface for reporting, that the test frameworks can simply rely on an call when they think it's appropriate.

```haxe
package travix;

class Logger {
  static public var inst(default, null):Logger = new PlatformSpecificImplementation();
  public function log(level:LogLevel, msg:String):Void;
  public function done(passed:Bool):Void;
}

enum LogLevel {
  Success;
  Info;
  Warning;
  Failure;
}
```

We could always compile with `-lib travix` (since travix must already be there anyway) and then the testing frameworks can react accordingly with `#if travix`.

**Comment by ciscoheat** [comment]
I agree with the interface, anything to avoid yet another dotfile.

**Comment by kevinresol** [comment]
For buddy, it will need `print`, `println` and `exit`. I am not sure if that is sufficient for other frameworks as well?
